[package]
name = "application"
version = "0.1.0"
edition = "2018"


[dependencies]
domain = { path = "../domain" }

async-trait = "0.1.51"

[dev-dependencies]
tokio = { version = "1.0",  features = ["full"] }
mockall = "0.10.2"