version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webapi
    volumes:
      - ./webapi/sql/create_users_table.sql:/docker-entrypoint-initdb.d/create_users_table.sql
    ports:
      - 5432:5432
    networks:
      - distributed_system
            
  mongodb:
    image: mongo
    container_name: inventory-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - distributed_system
  
  load-balancer:
    container_name: load-balancer
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/webapi.conf
    ports: 
      - 8080:8080
    networks:
      - distributed_system    

networks:
  distributed_system: