[package]
name = "infra"
version = "0.1.0"
edition = "2018"


[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }

log = "0.4.14"
env_logger = "0.9.0"
dotenv = "0.15.0"