version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017